### ISSUE TITLE
我通过ifconfig找到了ip地址填上去，但依然一直显示connect error,timeout。

### ISSUE THREAD

**Issue by hhbbww11221** [Karlsx/CyberDog_Ctrl#7]
问了chatgpt，似乎是grpc没在运行。于是用了ps aux | grep grpc检测，结果确实是监听不到grpc。但是我明明把那几个依赖都sudo安装了。我刷过一次机，目前是[V1.0.0.82]版本。不知道哪里出了问题

**Comment by hhbbww11221** [comment]
我刷机更新到了1.0.0.94后再尝试这个项目，成功了。原来不一定要HDMI连接到铁蛋本体才能运行，我用笔记本ros2使用这份代码，通过ifconfig查找ip地址，填了后也能运行。唯一比较难受的是好像必须要保证HDMI连接到一个显示器才可以运行这份代码。我试过开机cyberdog什么都不插不连接，然后通过笔记本上下的ROS2跑这个项目，但是没成功。

**Comment by QaisAshkar** [comment]
how did u manage to update firmware?
